version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
      - node --version
      - npm --version
      - npm install
      - cd ./ping && npm install && cd ..
  pre_build:
    commands:
      - cd ./ping && npm test && cd ..
  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
