AWSTemplateFormatVersion: 2010-09-09

Resources:
  RunTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "Run"
      AttributeDefinitions:
        -
          AttributeName: "requestId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "requestId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  LastRunDateTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "LastRunDate"
      AttributeDefinitions:
        -
          AttributeName: "alias"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "alias"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"


  ApplicantTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "Applicant"
      AttributeDefinitions:
        -
          AttributeName: "srCandidateId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "srCandidateId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

