AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes
#     Environment:
#       Variables:
#         TABLE_NAME: data-table

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180
    Handler: index.handler

Resources:
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ping/
      Environment:
        Variables:
          PARAM1: VALUE
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetApiEndpoint:
          Type: Api
          Properties:
            Method: get
            Path: /ping

  SlinkMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./slink-main/
      Environment:
        Variables:
          SR_API_TOKEN: override_me
          SR_CANDIDATE_SUMMARY_URL: https://api.smartrecruiters.com/candidates?updatedAfter=2018-02-01T10%3A15%3A00.500%2B00%3A00&status=OFFERED&subStatus=Offer Accepted
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetApiEndpoint:
          Type: Api
          Properties:
            Method: get
            Path: /slink

  SlinkMainFunction2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./slink-main/
      Environment:
        Variables:
          SR_API_TOKEN: override_me
          SR_CANDIDATE_SUMMARY_URL: https://api.smartrecruiters.com/candidates?updatedAfter=2018-02-01T10%3A15%3A00.500%2B00%3A00&status=OFFERED&subStatus=Offer Accepted
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetApiEndpoint:
          Type: Api
          Properties:
            Method: get
            Path: /slink2

Transform: AWS::Serverless-2016-10-31
