AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  ScheduledFunctionAlias:
    Type: String
    Description: Function Alias that is executed by the CW Event rule for scheduled runs.
    Default: PROD

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes
#     Environment:
#       Variables:
#         TABLE_NAME: data-table

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180
    Handler: index.handler

Resources:
  SlinkMainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./slink-main/
      AutoPublishAlias: STAGE
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetApiEndpoint:
          Type: Api
          Properties:
            Method: get
            Path: /slink

  SlinkIntroductionRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Invoke Slink Introduction Process"
      ScheduleExpression: "rate(15 minutes)"
      State: "ENABLED"
      Targets:
        -
          Arn: !Join
            - ':'
            - - !GetAtt SlinkMainFunction.Arn
              - !Ref ScheduledFunctionAlias
          Id: "SlinkMainV1"

  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Join
        - ':'
        - - !GetAtt SlinkMainFunction.Arn
          - !Ref ScheduledFunctionAlias

      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "SlinkIntroductionRule"
          - "Arn"

  ParameterStoreRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - 'lambda.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
                - 'iam:CreateRole'
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        Policies:
          -
            PolicyName: 'ParameterStoreSlinkAccess'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - 'ssm:GetParameter*'
                  Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/slink*'

Transform: AWS::Serverless-2016-10-31
