'use strict';

const LOG_INFO = 'INFO';
const LOG_DEBUG = 'DEBUG';
const LOG_ERROR = 'ERROR';
const LOG_WARN = 'WARN';

const STATUS_SKIPPED = 'Skipped';
const STATUS_SUCCESS = 'Succeeded';
const STATUS_FAILURE = 'Failed';

const REASON_ALREADY_ACTIVATED = 'Already activated';
const REASON_SAP_POST_FAILURE = 'SAP post failure';
const REASON_SR_POST_FAILURE = 'SR post failure';

const SR_OFFERED = 'OFFERED';
const SR_ONBOARDING = 'Onboarding';
const SR_OFFER_ACCEPTED = 'Offer Accepted';

const DYNAMO_DEFAULT_PORT = 8000;
const AWS_DEFAULT_REGION = 'us-east-1';

const SAP_DEFAULT_CHANGED_BY = '00001197';
const SAP_DEFAULT_ACTION = 'ACTIVE';
const SAP_DEFAULT_COMPANY = 'WT';
const SAP_DEFAULT_APPID = 'SR';
const SAP_DEFAULT_ZIPCODE = '40391';
const SAP_DEFAULT_STRING = 'NA';
const SAP_DEFAULT_MISSING_STRING = '';
const SAP_DEFAULT_SUCCESS_RESP = 'SUCCESS';
const SAP_DEFAULT_FAILURE_FLAGS = ['F'];
const SAP_DEFAULT_SUCCESS_FLAGS = ['T', 'S'];

/* These are the default values for SAP Post fields
 * NOTE: Since SAP is not validating these fields commented
 */
/* const SAP_DEFAULT_VALUE_DOB = '01-Jan-1900';
 * const SAP_DEFAULT_MIDDLE_NAME = '';
 * const SAP_DEFAULT_APPLICANT_GROUP = '5';
 * const SAP_DEFAULT_PERSONAL_AREA = 'USGA';
 * const SAP_DEFAULT_FORM_OF_ADDRESS = '1';
 * const SAP_DEFAULT_NATIONALITY = 'US';
 * const SAP_DEFAULT_LANGUAGE = 'EN';
 * const SAP_DEFAULT_CHANGED_BY = '00001197';
 * const SAP_DEFAULT_RECRUITER_ID = '10068175';
 * const SAP_DEFAULT_APPID = 'SR';
 * const SAP_DEFAULT_PROACTIVE_FLAG = 'Y';
 * const SAP_DEFAULT_CAREER_BAND = 'B2';
 * const SAP_DEFAULT_REPORTING_MANAGER = '117543';
 * const SAP_DEFAULT_JOB_CODE = '0';
 * const SAP_DEFAULT_EDUCATION_TYPE = '03';
 * const SAP_DEFAULT_BRANCH_OF_STUDY = '00027_02'; */

module.exports = {
  LOG_INFO,
  LOG_DEBUG,
  LOG_ERROR,
  LOG_WARN,
  STATUS_SKIPPED,
  STATUS_SUCCESS,
  STATUS_FAILURE,
  REASON_ALREADY_ACTIVATED,
  REASON_SAP_POST_FAILURE,
  REASON_SR_POST_FAILURE,
  SR_OFFERED,
  SR_ONBOARDING,
  SR_OFFER_ACCEPTED,
  DYNAMO_DEFAULT_PORT,
  AWS_DEFAULT_REGION,
  SAP_DEFAULT_CHANGED_BY,
  SAP_DEFAULT_ACTION,
  SAP_DEFAULT_COMPANY,
  SAP_DEFAULT_APPID,
  SAP_DEFAULT_ZIPCODE,
  SAP_DEFAULT_STRING,
  SAP_DEFAULT_MISSING_STRING,
  SAP_DEFAULT_SUCCESS_RESP,
  SAP_DEFAULT_FAILURE_FLAGS,
  SAP_DEFAULT_SUCCESS_FLAGS
};
